#workflow name
name : Hello

#when Workflow run Trigger
on: 
  push:  
      branches: [main]

# Jobs inside a Workflow
jobs:
  #name of Jobs
  Greet:
    runs-on: ubuntu-latest #github runner

    steps:
      - name: say heloo to users
        run: echo "Hello Kunal"
